FROM almalinux:8 
LABEL course="DevOps" \
      author="John Doe" \
      description="This is a sample Dockerfile for a web server" \
      version="1.0" \
      date="2023-10-01"\
      duration="2 hours" \
      status="active" 